require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ApprovedBuildsController do

  # This should return the minimal set of attributes required to create a valid
  # ApprovedBuild. As you add validations to ApprovedBuild, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "application_name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ApprovedBuildsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all approved_builds as @approved_builds" do
      approved_build = ApprovedBuild.create! valid_attributes
      get :index, {}, valid_session
      assigns(:approved_builds).should eq([approved_build])
    end
  end

  describe "GET show" do
    it "assigns the requested approved_build as @approved_build" do
      approved_build = ApprovedBuild.create! valid_attributes
      get :show, {:id => approved_build.to_param}, valid_session
      assigns(:approved_build).should eq(approved_build)
    end
  end

  describe "GET new" do
    it "assigns a new approved_build as @approved_build" do
      get :new, {}, valid_session
      assigns(:approved_build).should be_a_new(ApprovedBuild)
    end
  end

  describe "GET edit" do
    it "assigns the requested approved_build as @approved_build" do
      approved_build = ApprovedBuild.create! valid_attributes
      get :edit, {:id => approved_build.to_param}, valid_session
      assigns(:approved_build).should eq(approved_build)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ApprovedBuild" do
        expect {
          post :create, {:approved_build => valid_attributes}, valid_session
        }.to change(ApprovedBuild, :count).by(1)
      end

      it "assigns a newly created approved_build as @approved_build" do
        post :create, {:approved_build => valid_attributes}, valid_session
        assigns(:approved_build).should be_a(ApprovedBuild)
        assigns(:approved_build).should be_persisted
      end

      it "redirects to the created approved_build" do
        post :create, {:approved_build => valid_attributes}, valid_session
        response.should redirect_to(ApprovedBuild.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved approved_build as @approved_build" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApprovedBuild.any_instance.stub(:save).and_return(false)
        post :create, {:approved_build => { "application_name" => "invalid value" }}, valid_session
        assigns(:approved_build).should be_a_new(ApprovedBuild)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ApprovedBuild.any_instance.stub(:save).and_return(false)
        post :create, {:approved_build => { "application_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested approved_build" do
        approved_build = ApprovedBuild.create! valid_attributes
        # Assuming there are no other approved_builds in the database, this
        # specifies that the ApprovedBuild created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ApprovedBuild.any_instance.should_receive(:update_attributes).with({ "application_name" => "MyString" })
        put :update, {:id => approved_build.to_param, :approved_build => { "application_name" => "MyString" }}, valid_session
      end

      it "assigns the requested approved_build as @approved_build" do
        approved_build = ApprovedBuild.create! valid_attributes
        put :update, {:id => approved_build.to_param, :approved_build => valid_attributes}, valid_session
        assigns(:approved_build).should eq(approved_build)
      end

      it "redirects to the approved_build" do
        approved_build = ApprovedBuild.create! valid_attributes
        put :update, {:id => approved_build.to_param, :approved_build => valid_attributes}, valid_session
        response.should redirect_to(approved_build)
      end
    end

    describe "with invalid params" do
      it "assigns the approved_build as @approved_build" do
        approved_build = ApprovedBuild.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ApprovedBuild.any_instance.stub(:save).and_return(false)
        put :update, {:id => approved_build.to_param, :approved_build => { "application_name" => "invalid value" }}, valid_session
        assigns(:approved_build).should eq(approved_build)
      end

      it "re-renders the 'edit' template" do
        approved_build = ApprovedBuild.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ApprovedBuild.any_instance.stub(:save).and_return(false)
        put :update, {:id => approved_build.to_param, :approved_build => { "application_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested approved_build" do
      approved_build = ApprovedBuild.create! valid_attributes
      expect {
        delete :destroy, {:id => approved_build.to_param}, valid_session
      }.to change(ApprovedBuild, :count).by(-1)
    end

    it "redirects to the approved_builds list" do
      approved_build = ApprovedBuild.create! valid_attributes
      delete :destroy, {:id => approved_build.to_param}, valid_session
      response.should redirect_to(approved_builds_url)
    end
  end

end
