require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DeploymentRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # DeploymentRequest. As you add validations to DeploymentRequest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "package" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DeploymentRequestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all deployment_requests as @deployment_requests" do
      deployment_request = DeploymentRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:deployment_requests).should eq([deployment_request])
    end
  end

  describe "GET show" do
    it "assigns the requested deployment_request as @deployment_request" do
      deployment_request = DeploymentRequest.create! valid_attributes
      get :show, {:id => deployment_request.to_param}, valid_session
      assigns(:deployment_request).should eq(deployment_request)
    end
  end

  describe "GET new" do
    it "assigns a new deployment_request as @deployment_request" do
      get :new, {}, valid_session
      assigns(:deployment_request).should be_a_new(DeploymentRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested deployment_request as @deployment_request" do
      deployment_request = DeploymentRequest.create! valid_attributes
      get :edit, {:id => deployment_request.to_param}, valid_session
      assigns(:deployment_request).should eq(deployment_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DeploymentRequest" do
        expect {
          post :create, {:deployment_request => valid_attributes}, valid_session
        }.to change(DeploymentRequest, :count).by(1)
      end

      it "assigns a newly created deployment_request as @deployment_request" do
        post :create, {:deployment_request => valid_attributes}, valid_session
        assigns(:deployment_request).should be_a(DeploymentRequest)
        assigns(:deployment_request).should be_persisted
      end

      it "redirects to the created deployment_request" do
        post :create, {:deployment_request => valid_attributes}, valid_session
        response.should redirect_to(DeploymentRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved deployment_request as @deployment_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeploymentRequest.any_instance.stub(:save).and_return(false)
        post :create, {:deployment_request => { "package" => "invalid value" }}, valid_session
        assigns(:deployment_request).should be_a_new(DeploymentRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DeploymentRequest.any_instance.stub(:save).and_return(false)
        post :create, {:deployment_request => { "package" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested deployment_request" do
        deployment_request = DeploymentRequest.create! valid_attributes
        # Assuming there are no other deployment_requests in the database, this
        # specifies that the DeploymentRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DeploymentRequest.any_instance.should_receive(:update_attributes).with({ "package" => "MyString" })
        put :update, {:id => deployment_request.to_param, :deployment_request => { "package" => "MyString" }}, valid_session
      end

      it "assigns the requested deployment_request as @deployment_request" do
        deployment_request = DeploymentRequest.create! valid_attributes
        put :update, {:id => deployment_request.to_param, :deployment_request => valid_attributes}, valid_session
        assigns(:deployment_request).should eq(deployment_request)
      end

      it "redirects to the deployment_request" do
        deployment_request = DeploymentRequest.create! valid_attributes
        put :update, {:id => deployment_request.to_param, :deployment_request => valid_attributes}, valid_session
        response.should redirect_to(deployment_request)
      end
    end

    describe "with invalid params" do
      it "assigns the deployment_request as @deployment_request" do
        deployment_request = DeploymentRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeploymentRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => deployment_request.to_param, :deployment_request => { "package" => "invalid value" }}, valid_session
        assigns(:deployment_request).should eq(deployment_request)
      end

      it "re-renders the 'edit' template" do
        deployment_request = DeploymentRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DeploymentRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => deployment_request.to_param, :deployment_request => { "package" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested deployment_request" do
      deployment_request = DeploymentRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => deployment_request.to_param}, valid_session
      }.to change(DeploymentRequest, :count).by(-1)
    end

    it "redirects to the deployment_requests list" do
      deployment_request = DeploymentRequest.create! valid_attributes
      delete :destroy, {:id => deployment_request.to_param}, valid_session
      response.should redirect_to(deployment_requests_url)
    end
  end

end
