require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JumpPageLinksController do

  # This should return the minimal set of attributes required to create a valid
  # JumpPageLink. As you add validations to JumpPageLink, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JumpPageLinksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all jump_page_links as @jump_page_links" do
      jump_page_link = JumpPageLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:jump_page_links).should eq([jump_page_link])
    end
  end

  describe "GET show" do
    it "assigns the requested jump_page_link as @jump_page_link" do
      jump_page_link = JumpPageLink.create! valid_attributes
      get :show, {:id => jump_page_link.to_param}, valid_session
      assigns(:jump_page_link).should eq(jump_page_link)
    end
  end

  describe "GET new" do
    it "assigns a new jump_page_link as @jump_page_link" do
      get :new, {}, valid_session
      assigns(:jump_page_link).should be_a_new(JumpPageLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested jump_page_link as @jump_page_link" do
      jump_page_link = JumpPageLink.create! valid_attributes
      get :edit, {:id => jump_page_link.to_param}, valid_session
      assigns(:jump_page_link).should eq(jump_page_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JumpPageLink" do
        expect {
          post :create, {:jump_page_link => valid_attributes}, valid_session
        }.to change(JumpPageLink, :count).by(1)
      end

      it "assigns a newly created jump_page_link as @jump_page_link" do
        post :create, {:jump_page_link => valid_attributes}, valid_session
        assigns(:jump_page_link).should be_a(JumpPageLink)
        assigns(:jump_page_link).should be_persisted
      end

      it "redirects to the created jump_page_link" do
        post :create, {:jump_page_link => valid_attributes}, valid_session
        response.should redirect_to(JumpPageLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jump_page_link as @jump_page_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        JumpPageLink.any_instance.stub(:save).and_return(false)
        post :create, {:jump_page_link => { "name" => "invalid value" }}, valid_session
        assigns(:jump_page_link).should be_a_new(JumpPageLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        JumpPageLink.any_instance.stub(:save).and_return(false)
        post :create, {:jump_page_link => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jump_page_link" do
        jump_page_link = JumpPageLink.create! valid_attributes
        # Assuming there are no other jump_page_links in the database, this
        # specifies that the JumpPageLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        JumpPageLink.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => jump_page_link.to_param, :jump_page_link => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested jump_page_link as @jump_page_link" do
        jump_page_link = JumpPageLink.create! valid_attributes
        put :update, {:id => jump_page_link.to_param, :jump_page_link => valid_attributes}, valid_session
        assigns(:jump_page_link).should eq(jump_page_link)
      end

      it "redirects to the jump_page_link" do
        jump_page_link = JumpPageLink.create! valid_attributes
        put :update, {:id => jump_page_link.to_param, :jump_page_link => valid_attributes}, valid_session
        response.should redirect_to(jump_page_link)
      end
    end

    describe "with invalid params" do
      it "assigns the jump_page_link as @jump_page_link" do
        jump_page_link = JumpPageLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JumpPageLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => jump_page_link.to_param, :jump_page_link => { "name" => "invalid value" }}, valid_session
        assigns(:jump_page_link).should eq(jump_page_link)
      end

      it "re-renders the 'edit' template" do
        jump_page_link = JumpPageLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JumpPageLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => jump_page_link.to_param, :jump_page_link => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jump_page_link" do
      jump_page_link = JumpPageLink.create! valid_attributes
      expect {
        delete :destroy, {:id => jump_page_link.to_param}, valid_session
      }.to change(JumpPageLink, :count).by(-1)
    end

    it "redirects to the jump_page_links list" do
      jump_page_link = JumpPageLink.create! valid_attributes
      delete :destroy, {:id => jump_page_link.to_param}, valid_session
      response.should redirect_to(jump_page_links_url)
    end
  end

end
