require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AppSyncReportsController do

  # This should return the minimal set of attributes required to create a valid
  # AppSyncReport. As you add validations to AppSyncReport, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AppSyncReportsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all app_sync_reports as @app_sync_reports" do
      app_sync_report = AppSyncReport.create! valid_attributes
      get :index, {}, valid_session
      assigns(:app_sync_reports).should eq([app_sync_report])
    end
  end

  describe "GET show" do
    it "assigns the requested app_sync_report as @app_sync_report" do
      app_sync_report = AppSyncReport.create! valid_attributes
      get :show, {:id => app_sync_report.to_param}, valid_session
      assigns(:app_sync_report).should eq(app_sync_report)
    end
  end

  describe "GET new" do
    it "assigns a new app_sync_report as @app_sync_report" do
      get :new, {}, valid_session
      assigns(:app_sync_report).should be_a_new(AppSyncReport)
    end
  end

  describe "GET edit" do
    it "assigns the requested app_sync_report as @app_sync_report" do
      app_sync_report = AppSyncReport.create! valid_attributes
      get :edit, {:id => app_sync_report.to_param}, valid_session
      assigns(:app_sync_report).should eq(app_sync_report)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AppSyncReport" do
        expect {
          post :create, {:app_sync_report => valid_attributes}, valid_session
        }.to change(AppSyncReport, :count).by(1)
      end

      it "assigns a newly created app_sync_report as @app_sync_report" do
        post :create, {:app_sync_report => valid_attributes}, valid_session
        assigns(:app_sync_report).should be_a(AppSyncReport)
        assigns(:app_sync_report).should be_persisted
      end

      it "redirects to the created app_sync_report" do
        post :create, {:app_sync_report => valid_attributes}, valid_session
        response.should redirect_to(AppSyncReport.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved app_sync_report as @app_sync_report" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppSyncReport.any_instance.stub(:save).and_return(false)
        post :create, {:app_sync_report => { "name" => "invalid value" }}, valid_session
        assigns(:app_sync_report).should be_a_new(AppSyncReport)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AppSyncReport.any_instance.stub(:save).and_return(false)
        post :create, {:app_sync_report => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested app_sync_report" do
        app_sync_report = AppSyncReport.create! valid_attributes
        # Assuming there are no other app_sync_reports in the database, this
        # specifies that the AppSyncReport created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AppSyncReport.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => app_sync_report.to_param, :app_sync_report => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested app_sync_report as @app_sync_report" do
        app_sync_report = AppSyncReport.create! valid_attributes
        put :update, {:id => app_sync_report.to_param, :app_sync_report => valid_attributes}, valid_session
        assigns(:app_sync_report).should eq(app_sync_report)
      end

      it "redirects to the app_sync_report" do
        app_sync_report = AppSyncReport.create! valid_attributes
        put :update, {:id => app_sync_report.to_param, :app_sync_report => valid_attributes}, valid_session
        response.should redirect_to(app_sync_report)
      end
    end

    describe "with invalid params" do
      it "assigns the app_sync_report as @app_sync_report" do
        app_sync_report = AppSyncReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppSyncReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => app_sync_report.to_param, :app_sync_report => { "name" => "invalid value" }}, valid_session
        assigns(:app_sync_report).should eq(app_sync_report)
      end

      it "re-renders the 'edit' template" do
        app_sync_report = AppSyncReport.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AppSyncReport.any_instance.stub(:save).and_return(false)
        put :update, {:id => app_sync_report.to_param, :app_sync_report => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested app_sync_report" do
      app_sync_report = AppSyncReport.create! valid_attributes
      expect {
        delete :destroy, {:id => app_sync_report.to_param}, valid_session
      }.to change(AppSyncReport, :count).by(-1)
    end

    it "redirects to the app_sync_reports list" do
      app_sync_report = AppSyncReport.create! valid_attributes
      delete :destroy, {:id => app_sync_report.to_param}, valid_session
      response.should redirect_to(app_sync_reports_url)
    end
  end

end
