require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EsrWorksController do

  # This should return the minimal set of attributes required to create a valid
  # EsrWork. As you add validations to EsrWork, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EsrWorksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all esr_works as @esr_works" do
      esr_work = EsrWork.create! valid_attributes
      get :index, {}, valid_session
      assigns(:esr_works).should eq([esr_work])
    end
  end

  describe "GET show" do
    it "assigns the requested esr_work as @esr_work" do
      esr_work = EsrWork.create! valid_attributes
      get :show, {:id => esr_work.to_param}, valid_session
      assigns(:esr_work).should eq(esr_work)
    end
  end

  describe "GET new" do
    it "assigns a new esr_work as @esr_work" do
      get :new, {}, valid_session
      assigns(:esr_work).should be_a_new(EsrWork)
    end
  end

  describe "GET edit" do
    it "assigns the requested esr_work as @esr_work" do
      esr_work = EsrWork.create! valid_attributes
      get :edit, {:id => esr_work.to_param}, valid_session
      assigns(:esr_work).should eq(esr_work)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EsrWork" do
        expect {
          post :create, {:esr_work => valid_attributes}, valid_session
        }.to change(EsrWork, :count).by(1)
      end

      it "assigns a newly created esr_work as @esr_work" do
        post :create, {:esr_work => valid_attributes}, valid_session
        assigns(:esr_work).should be_a(EsrWork)
        assigns(:esr_work).should be_persisted
      end

      it "redirects to the created esr_work" do
        post :create, {:esr_work => valid_attributes}, valid_session
        response.should redirect_to(EsrWork.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved esr_work as @esr_work" do
        # Trigger the behavior that occurs when invalid params are submitted
        EsrWork.any_instance.stub(:save).and_return(false)
        post :create, {:esr_work => { "name" => "invalid value" }}, valid_session
        assigns(:esr_work).should be_a_new(EsrWork)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EsrWork.any_instance.stub(:save).and_return(false)
        post :create, {:esr_work => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested esr_work" do
        esr_work = EsrWork.create! valid_attributes
        # Assuming there are no other esr_works in the database, this
        # specifies that the EsrWork created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EsrWork.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => esr_work.to_param, :esr_work => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested esr_work as @esr_work" do
        esr_work = EsrWork.create! valid_attributes
        put :update, {:id => esr_work.to_param, :esr_work => valid_attributes}, valid_session
        assigns(:esr_work).should eq(esr_work)
      end

      it "redirects to the esr_work" do
        esr_work = EsrWork.create! valid_attributes
        put :update, {:id => esr_work.to_param, :esr_work => valid_attributes}, valid_session
        response.should redirect_to(esr_work)
      end
    end

    describe "with invalid params" do
      it "assigns the esr_work as @esr_work" do
        esr_work = EsrWork.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EsrWork.any_instance.stub(:save).and_return(false)
        put :update, {:id => esr_work.to_param, :esr_work => { "name" => "invalid value" }}, valid_session
        assigns(:esr_work).should eq(esr_work)
      end

      it "re-renders the 'edit' template" do
        esr_work = EsrWork.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EsrWork.any_instance.stub(:save).and_return(false)
        put :update, {:id => esr_work.to_param, :esr_work => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested esr_work" do
      esr_work = EsrWork.create! valid_attributes
      expect {
        delete :destroy, {:id => esr_work.to_param}, valid_session
      }.to change(EsrWork, :count).by(-1)
    end

    it "redirects to the esr_works list" do
      esr_work = EsrWork.create! valid_attributes
      delete :destroy, {:id => esr_work.to_param}, valid_session
      response.should redirect_to(esr_works_url)
    end
  end

end
