require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LatestReleasesController do

  # This should return the minimal set of attributes required to create a valid
  # LatestRelease. As you add validations to LatestRelease, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "tvl-webapp" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LatestReleasesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all latest_releases as @latest_releases" do
      latest_release = LatestRelease.create! valid_attributes
      get :index, {}, valid_session
      assigns(:latest_releases).should eq([latest_release])
    end
  end

  describe "GET show" do
    it "assigns the requested latest_release as @latest_release" do
      latest_release = LatestRelease.create! valid_attributes
      get :show, {:id => latest_release.to_param}, valid_session
      assigns(:latest_release).should eq(latest_release)
    end
  end

  describe "GET new" do
    it "assigns a new latest_release as @latest_release" do
      get :new, {}, valid_session
      assigns(:latest_release).should be_a_new(LatestRelease)
    end
  end

  describe "GET edit" do
    it "assigns the requested latest_release as @latest_release" do
      latest_release = LatestRelease.create! valid_attributes
      get :edit, {:id => latest_release.to_param}, valid_session
      assigns(:latest_release).should eq(latest_release)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LatestRelease" do
        expect {
          post :create, {:latest_release => valid_attributes}, valid_session
        }.to change(LatestRelease, :count).by(1)
      end

      it "assigns a newly created latest_release as @latest_release" do
        post :create, {:latest_release => valid_attributes}, valid_session
        assigns(:latest_release).should be_a(LatestRelease)
        assigns(:latest_release).should be_persisted
      end

      it "redirects to the created latest_release" do
        post :create, {:latest_release => valid_attributes}, valid_session
        response.should redirect_to(LatestRelease.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved latest_release as @latest_release" do
        # Trigger the behavior that occurs when invalid params are submitted
        LatestRelease.any_instance.stub(:save).and_return(false)
        post :create, {:latest_release => { "name" => "invalid value" }}, valid_session
        assigns(:latest_release).should be_a_new(LatestRelease)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LatestRelease.any_instance.stub(:save).and_return(false)
        post :create, {:latest_release => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested latest_release" do
        latest_release = LatestRelease.create! valid_attributes
        # Assuming there are no other latest_releases in the database, this
        # specifies that the LatestRelease created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LatestRelease.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => latest_release.to_param, :latest_release => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested latest_release as @latest_release" do
        latest_release = LatestRelease.create! valid_attributes
        put :update, {:id => latest_release.to_param, :latest_release => valid_attributes}, valid_session
        assigns(:latest_release).should eq(latest_release)
      end

      it "redirects to the latest_release" do
        latest_release = LatestRelease.create! valid_attributes
        put :update, {:id => latest_release.to_param, :latest_release => valid_attributes}, valid_session
        response.should redirect_to(latest_release)
      end
    end

    describe "with invalid params" do
      it "assigns the latest_release as @latest_release" do
        latest_release = LatestRelease.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LatestRelease.any_instance.stub(:save).and_return(false)
        put :update, {:id => latest_release.to_param, :latest_release => { "name" => "invalid value" }}, valid_session
        assigns(:latest_release).should eq(latest_release)
      end

      it "re-renders the 'edit' template" do
        latest_release = LatestRelease.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LatestRelease.any_instance.stub(:save).and_return(false)
        put :update, {:id => latest_release.to_param, :latest_release => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested latest_release" do
      latest_release = LatestRelease.create! valid_attributes
      expect {
        delete :destroy, {:id => latest_release.to_param}, valid_session
      }.to change(LatestRelease, :count).by(-1)
    end

    it "redirects to the latest_releases list" do
      latest_release = LatestRelease.create! valid_attributes
      delete :destroy, {:id => latest_release.to_param}, valid_session
      response.should redirect_to(latest_releases_url)
    end
  end

end
