require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RetriesController do

  # This should return the minimal set of attributes required to create a valid
  # Retry. As you add validations to Retry, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "workflow_state" => "started" }
  end

  def system_conf_attributes
    { "num_latest_releases" => 4,
      "in_effect" => true } 
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RetriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe Retry do
      before(:all) do
        @conf = SystemConfiguration.create system_conf_attributes
        @conf.save
      end

  describe "has SystemConfiguration.in_effect" do
    it "always has a SystemConfiguration.in_effect" do
      conf = SystemConfiguration.in_effect
      conf.should be_a(SystemConfiguration)
    end
  end
  
  describe "GET #index" do
    it "assigns all retries as @retries" do
      ret = Retry.create! valid_attributes
      get :index, {}, valid_session
      assigns(:retries).should eq([ret])
    end
  end

  describe "GET #show" do
    it "assigns the requested ret as @ret" do
      ret = Retry.create! valid_attributes
      get :show, {:id => ret.to_param}, valid_session
      assigns(:ret).should eq(ret)
    end
  end

  describe "GET #new" do
    it "assigns a new ret as @ret" do
      get :new, {}, valid_session
      assigns(:ret).should be_a_new(Retry)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ret as @ret" do
      ret = Retry.create! valid_attributes
      get :edit, {:id => ret.to_param}, valid_session
      assigns(:ret).should eq(ret)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Retry" do
        expect {
          post :create, {:ret => valid_attributes}, valid_session
        }.to change(Retry, :count).by(1)
      end

      it "assigns a newly created ret as @ret" do
        post :create, {:ret => valid_attributes}, valid_session
        assigns(:ret).should be_a(Retry)
        assigns(:ret).should be_persisted
      end

      it "redirects to the created ret" do
        post :create, {:ret => valid_attributes}, valid_session
        response.should redirect_to(Retry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ret as @ret" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retry.any_instance.stub(:save).and_return(false)
        post :create, {:ret => { "workflow_state" => "invalid value" }}, valid_session
        assigns(:ret).should be_a_new(Retry)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Retry.any_instance.stub(:save).and_return(false)
        post :create, {:ret => { "workflow_state" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ret" do
        ret = Retry.create! valid_attributes
        # Assuming there are no other retries in the database, this
        # specifies that the Retry created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Retry.any_instance.should_receive(:update_attributes).with({ "workflow_state" => "MyString" })
        put :update, {:id => ret.to_param, :ret => { "workflow_state" => "MyString" }}, valid_session
      end

      it "assigns the requested ret as @ret" do
        ret = Retry.create! valid_attributes
        put :update, {:id => ret.to_param, :ret => valid_attributes}, valid_session
        assigns(:ret).should eq(ret)
      end

      it "redirects to the ret" do
        ret = Retry.create! valid_attributes
        put :update, {:id => ret.to_param, :ret => valid_attributes}, valid_session
        response.should redirect_to(ret)
      end
    end

    describe "with invalid params" do
      it "assigns the ret as @ret" do
        ret = Retry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retry.any_instance.stub(:save).and_return(false)
        put :update, {:id => ret.to_param, :ret => { "workflow_state" => "invalid value" }}, valid_session
        assigns(:ret).should eq(ret)
      end

      it "re-renders the 'edit' template" do
        ret = Retry.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Retry.any_instance.stub(:save).and_return(false)
        put :update, {:id => ret.to_param, :ret => { "workflow_state" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ret" do
      ret = Retry.create! valid_attributes
      expect {
        delete :destroy, {:id => ret.to_param}, valid_session
      }.to change(Retry, :count).by(-1)
    end

    it "redirects to the retries list" do
      ret = Retry.create! valid_attributes
      delete :destroy, {:id => ret.to_param}, valid_session
      response.should redirect_to(retries_url)
    end
  end

  end
end
